
import React, { useState, useRef, useEffect } from 'react';
import Card from '../common/Card';
import Button from '../common/Button';
import { useSpeechToText } from '../../hooks/useSpeechToText';
import { cn } from '../../utils/classNames';
import { FeedItemData } from '../../types';

interface UploadVideoModalProps {
    onClose: () => void;
    onVideoUpload: (video: FeedItemData) => void;
}

type CreativeMode = '10m' | '60s' | '15s' | 'PHOTO' | 'TEXT';
type UploadStep = 'EDITOR' | 'DETAILS' | 'PROCESSING' | 'SUCCESS';

const UploadVideoModal: React.FC<UploadVideoModalProps> = ({ onClose, onVideoUpload }) => {
    const fileInputRef = useRef<HTMLInputElement>(null);
    const [step, setStep] = useState<UploadStep>('EDITOR');
    const [activeMode, setActiveMode] = useState<CreativeMode>('60s');
    const [selectedVideoUrl, setSelectedVideoUrl] = useState<string | null>(null);
    
    // Processing state
    const [processingStage, setProcessingStage] = useState(0);
    
    // Form State
    const [title, setTitle] = useState('');
    const [topic, setTopic] = useState('');
    const [description, setDescription] = useState('');

    const { isListening: isTitleListening, startListening: startTitleListening } = useSpeechToText((text) => setTitle(prev => (prev ? `${prev} ${text}` : text)));
    const { isListening: isDescListening, startListening: startDescListening } = useSpeechToText((text) => setDescription(prev => (prev ? `${prev} ${text}` : text)));

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            const url = URL.createObjectURL(file);
            setSelectedVideoUrl(url);
        }
    };

    const handlePublish = () => {
        if (!selectedVideoUrl) return;

        setStep('PROCESSING');
        const stages = [
            "Optimizing educational video...",
            "AI generating lesson context...",
            "Indexing visual patterns...",
            "Finalizing your masterpiece..."
        ];

        let current = 0;
        const interval = setInterval(() => {
            current++;
            setProcessingStage(current);
            if (current >= stages.length) {
                clearInterval(interval);
                
                // Construct the actual FeedItemData
                const newVideo: FeedItemData = {
                    id: `uploaded-${Date.now()}`,
                    topic: topic || 'General Learning',
                    title: title || 'New Lesson',
                    description: description || 'No description provided.',
                    videoPosterUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=2070&auto=format&fit=crop',
                    videoUrl: selectedVideoUrl,
                    author: {
                        name: 'Me (Scholar)',
                        avatarUrl: 'https://i.pravatar.cc/100?u=me',
                        isVerified: false
                    },
                    stats: { likes: '0', comments: '0', shares: '0' },
                    transcript: ["Interactive lesson generated by creator...", "Ready for AI co-pilot integration."]
                };

                onVideoUpload(newVideo);
                setStep('SUCCESS');
            }
        }, 600);
    };

    const processingStages = [
        "Optimizing educational video...",
        "AI generating lesson context...",
        "Indexing visual patterns...",
        "Finalizing your masterpiece..."
    ];

    return (
        <div className="absolute inset-0 z-[60] bg-black text-white overflow-hidden animate-in fade-in duration-300">
            <input 
                type="file" 
                ref={fileInputRef} 
                accept="video/*" 
                className="hidden" 
                onChange={handleFileChange} 
            />

            {/* EDITOR VIEW */}
            {step === 'EDITOR' && (
                <div className="h-full w-full flex flex-col relative">
                    <div className="absolute top-0 inset-x-0 z-20 flex items-center justify-between px-6 pt-12">
                        <button onClick={onClose} className="text-white hover:scale-110 transition-transform">
                            <span className="material-symbols-outlined text-3xl">close</span>
                        </button>
                        
                        <button className="flex items-center gap-2 bg-white/10 backdrop-blur-md border border-white/20 rounded-full px-4 py-1.5 text-sm font-bold shadow-lg">
                            <span className="material-symbols-outlined text-xl">music_note</span>
                            Original sound
                        </button>

                        <button onClick={() => fileInputRef.current?.click()} className="text-white hover:rotate-12 transition-transform">
                            <span className="material-symbols-outlined text-3xl">upload_file</span>
                        </button>
                    </div>

                    <div className="flex-1 flex items-center justify-center relative overflow-hidden bg-black">
                        {selectedVideoUrl ? (
                            <video 
                                src={selectedVideoUrl} 
                                className="w-full h-full object-contain" 
                                autoPlay 
                                loop 
                                muted 
                                playsInline
                            />
                        ) : (
                            <div className="flex flex-col items-center gap-4 text-white/30">
                                <span className="material-symbols-outlined text-7xl animate-pulse">movie</span>
                                <p className="text-sm font-bold tracking-widest uppercase">Select a video to begin</p>
                                <Button onClick={() => fileInputRef.current?.click()} size="sm">Open Gallery</Button>
                            </div>
                        )}
                    </div>

                    <div className="bg-gradient-to-t from-black via-black/80 to-transparent pt-10 pb-8 px-4 relative z-20">
                        <div className="flex items-center justify-center gap-6 mb-8 text-[11px] font-bold tracking-widest text-white/50 uppercase">
                            {['10m', '60s', '15s', 'PHOTO'].map((mode) => (
                                <button 
                                    key={mode} 
                                    onClick={() => setActiveMode(mode as CreativeMode)}
                                    className={cn("transition-colors", activeMode === mode ? "text-white" : "hover:text-white/80")}
                                >
                                    {mode}
                                </button>
                            ))}
                        </div>

                        <div className="flex items-center justify-center">
                            <button 
                                onClick={() => selectedVideoUrl ? setStep('DETAILS') : fileInputRef.current?.click()}
                                className={cn(
                                    "size-20 rounded-full p-1 border-[4px] shadow-xl active:scale-95 transition-all relative group",
                                    selectedVideoUrl ? "bg-primary border-primary/20" : "bg-white border-white/20"
                                )}
                            >
                                <div className="w-full h-full rounded-full border-2 border-black/10 flex items-center justify-center">
                                     <span className={cn("material-symbols-outlined text-3xl", selectedVideoUrl ? "text-white" : "text-black")}>
                                        {selectedVideoUrl ? 'check' : 'add'}
                                     </span>
                                </div>
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* DETAILS VIEW */}
            {step === 'DETAILS' && (
                <div className="h-full flex flex-col bg-[#0F0F13]">
                    <div className="p-4 border-b border-white/5 flex justify-between items-center bg-white/5 pt-12">
                        <button onClick={() => setStep('EDITOR')} className="text-white/60">
                            <span className="material-symbols-outlined">arrow_back</span>
                        </button>
                        <h2 className="text-lg font-bold font-display text-white">Lesson Details</h2>
                        <div className="w-8"></div>
                    </div>

                    <div className="flex-1 overflow-y-auto p-6 space-y-6">
                        <div className="aspect-[9/16] w-32 bg-black rounded-xl mx-auto border border-white/20 overflow-hidden relative shadow-2xl">
                             <video src={selectedVideoUrl!} className="w-full h-full object-cover opacity-80" muted />
                        </div>

                        <div className="space-y-4">
                            <div>
                                <label className="text-xs font-bold text-white/40 uppercase mb-1.5 block">Title</label>
                                <div className="relative">
                                    <input 
                                        type="text" 
                                        value={title}
                                        onChange={(e) => setTitle(e.target.value)}
                                        className="w-full bg-white/5 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-primary outline-none pr-12"
                                        placeholder="Give your lesson a title..."
                                    />
                                    <button onClick={startTitleListening} className={cn("absolute right-4 top-1/2 -translate-y-1/2", isTitleListening && "text-red-500 animate-pulse")}>
                                        <span className="material-symbols-outlined text-xl">mic</span>
                                    </button>
                                </div>
                            </div>
                            
                            <div>
                                <label className="text-xs font-bold text-white/40 uppercase mb-1.5 block">Topic</label>
                                <select 
                                    value={topic}
                                    onChange={(e) => setTopic(e.target.value)}
                                    className="w-full bg-white/5 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-primary outline-none"
                                >
                                    <option value="">Select subject...</option>
                                    <option value="Physics">Physics</option>
                                    <option value="Computer Science">Computer Science</option>
                                    <option value="Biology">Biology</option>
                                    <option value="Creative Arts">Creative Arts</option>
                                </select>
                            </div>

                            <div>
                                <label className="text-xs font-bold text-white/40 uppercase mb-1.5 block">Description</label>
                                <div className="relative">
                                    <textarea 
                                        value={description}
                                        onChange={(e) => setDescription(e.target.value)}
                                        className="w-full bg-white/5 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-primary outline-none h-24 resize-none pr-12"
                                        placeholder="Explain what scholars will learn..."
                                    />
                                    <button onClick={startDescListening} className={cn("absolute right-4 top-4", isDescListening && "text-red-500 animate-pulse")}>
                                        <span className="material-symbols-outlined text-xl">mic</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="p-6 border-t border-white/5 bg-black/40">
                        <Button onClick={handlePublish} fullWidth size="lg">
                            <span className="material-symbols-outlined mr-2">publish</span>
                            Post to Feed
                        </Button>
                    </div>
                </div>
            )}

            {/* PROCESSING VIEW */}
            {step === 'PROCESSING' && (
                <div className="h-full flex flex-col items-center justify-center p-10 text-center">
                    <div className="relative size-32 mb-8">
                        <div className="absolute inset-0 border-4 border-white/10 rounded-full"></div>
                        <div className="absolute inset-0 border-4 border-primary rounded-full border-t-transparent animate-spin"></div>
                        <div className="absolute inset-0 flex items-center justify-center">
                            <span className="material-symbols-outlined text-5xl text-primary animate-pulse">auto_fix_high</span>
                        </div>
                    </div>
                    <h3 className="text-2xl font-bold mb-2">GenAI Processing...</h3>
                    <p className="text-white/40">{processingStages[Math.min(processingStage, processingStages.length - 1)]}</p>
                </div>
            )}

            {/* SUCCESS VIEW */}
            {step === 'SUCCESS' && (
                <div className="h-full flex flex-col items-center justify-center p-10 text-center animate-in zoom-in duration-500">
                    <div className="size-24 bg-green-500 rounded-full flex items-center justify-center shadow-[0_0_30px_rgba(34,197,94,0.5)] mb-8">
                        <span className="material-symbols-outlined text-6xl text-white">check</span>
                    </div>
                    <h2 className="text-3xl font-bold mb-2">Lesson Published!</h2>
                    <p className="text-white/60 mb-12">Scholars can now learn from your creation.</p>
                    <Button onClick={onClose} fullWidth size="lg">Done</Button>
                </div>
            )}
        </div>
    );
};

export default UploadVideoModal;
